resources:
  - ../../base
helmCharts:
  - name: api-gateway
    path: ../../helm/api-gateway
    valuesFile: values-api-gateway.yaml
    namespace: mibo
  - name: app-host
    path: ../../helm/app-host
    valuesFile: values-app-host.yaml
    namespace: mibo
  - name: calendar-agent
    path: ../../helm/calendar-agent
    valuesFile: values-calendar-agent.yaml
    namespace: mibo
  - name: conversation-service
    path: ../../helm/conversation-service
    valuesFile: values-conversation-service.yaml
    namespace: mibo
  - name: visualisation-service
    path: ../../helm/visualisation-service
    valuesFile: values-visualisation-service.yaml
    namespace: mibo
  - name: weather-data-service
    path: ../../helm/weather-data-service
    valuesFile: values-weather-data-service.yaml
    namespace: mibo