apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - ../../base

helmCharts:
  - name: api-gateway
    path: ../../helm/api-gateway
    valuesFile: values-api-gateway.yaml
    namespace: prod
  - name: app-host
    path: ../../helm/app-host
    valuesFile: values-app-host.yaml
    namespace: prod
  - name: calendar-agent
    path: ../../helm/calendar-agent
    valuesFile: values-calendar-agent.yaml
    namespace: prod
  - name: conversation-service
    path: ../../helm/conversation-service
    valuesFile: values-conversation-service.yaml
    namespace: prod
  - name: visualisation-service
    path: ../../helm/visualisation-service
    valuesFile: values-visualisation-service.yaml
    namespace: prod
  - name: identity-service
    path: ../../helm/identity-service
    valuesFile: values-identity-service.yaml
    namespace: prod
    
